import { createFileRoute } from "@tanstack/react-router";
import { Church, Globe2, HandHeart, Users } from "lucide-react";
import { PageIntro, SectionTitle } from "@/components/page-parts";
import { assets } from "@/lib/site-assets";
import { pageHead } from "@/lib/site-data";

export const Route = createFileRoute("/about")({ head: () => pageHead("About Us", "Our story, values, founders, and volunteer leadership.", "/about"), component: About });
const values = [[Church,"Faith","Rooted in Catholic tradition — the Mass, sacraments, and lifelong formation."],[Globe2,"Culture","Celebrating the rich heritage of Indian Christianity across every region."],[Users,"Community","A home away from home for families across Central Texas."],[HandHeart,"Service","Reaching out — to India, to Austin, to those in need."]] as const;
const leaders = [
  [assets.melissa,"Melissa Sacrafamilia","President","I moved to Texas in 2015 with my family. We have been members of ICA for the last 10 years and have made many friends that have become family to us. This is my second time serving on the board of directors and I look forward to continuing the great work done by our community."],
  [assets.praveen,"Praveen D'Souza","Vice President","An engineer-turned-entrepreneur with nearly three decades in the semiconductor industry, I made a major life transition to become a full-time farmer on the outskirts of Austin, focused on regenerative livestock management and rotational grazing."],
  [assets.aldila,"Aldila Lobo","Director","Since our family moved to Austin in 2007, the ICA has been a welcoming beacon — providing belonging and community that has only grown stronger. For our children, it has been an invaluable foundation for lifelong friendships and cultural roots."],
  [assets.blaise,"Blaise D'Mello","Director","I've been part of the ICA since its early days and have watched it grow into a thriving community over 20+ years. ICA has always been an important part of my family's life."],
  [assets.carol,"Carol D'Costa","Director","I became a member of the ICA in 2009, and from the start it has been a true home away from home. Some of my fondest memories come from ICA gatherings."],
];
function About(){return <><PageIntro eyebrow="Our Story" title="A faith-and-culture home in Central Texas"><p>The India Catholic Association (ICA) of Central Texas is a registered non-profit organization based in Austin, and founded in 2001. Its mission is to preserve the cultural heritage and spiritual values of its members, and to make a positive impact on the local and global community through charitable projects.</p><p className="mt-4">ICA organizes year-round community events, its annual Taste of India fundraiser, Lenten retreats, and first Friday prayer meetings.</p></PageIntro><section className="site-container py-20"><SectionTitle eyebrow="What we stand for" title="Our Values"/><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map(([Icon,title,text])=><article key={title} className="warm-card p-6"><span className="grid size-11 place-items-center rounded-full bg-accent/35 text-primary"><Icon size={21}/></span><h3 className="mt-5 font-display text-xl font-semibold text-primary">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></article>)}</div></section><section className="bg-muted/55 py-20"><div className="site-container"><SectionTitle eyebrow="With gratitude" title="Founders"/><div className="mt-8 grid max-w-xl grid-cols-2 gap-5">{[[assets.eula,"Eula Sequeira"],[assets.austin,"Austin Sequeira"]].map(([src,name])=><figure key={name}><img src={src} alt={`${name}, founder of ICA`} className="aspect-square w-full rounded-lg object-cover"/><figcaption className="mt-3 font-display text-xl font-semibold text-primary">{name}</figcaption></figure>)}</div></div></section><section className="site-container py-20"><SectionTitle eyebrow="Leadership" title="Board of Directors" description="Our board is entirely volunteer-run — parishioners who give their time to keep this community thriving."/><div className="mt-9 grid gap-7 lg:grid-cols-2">{leaders.map(([src,name,role,bio])=><article key={name} className="flex gap-5 border-t border-border pt-6"><img src={src} alt={`${name}, ${role}`} className="size-28 shrink-0 rounded-lg object-cover sm:size-36"/><div><h3 className="font-display text-2xl font-semibold text-primary">{name}</h3><p className="mt-1 text-xs font-bold uppercase text-accent-foreground">{role}</p><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{bio}</p></div></article>)}</div></section></>}