import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro } from "@/components/page-parts";
import { pageHead } from "@/lib/site-data";

export const Route = createFileRoute("/taste-of-india/funds-disbursement")({ head: () => pageHead("Funds Disbursement Committee", "The governing guidelines for Taste of India charitable funding.", "/taste-of-india/funds-disbursement"), component: Funds });
const sections = [
  ["Purpose and composition", ["The Funds Disbursement Committee was established in 2013. It is composed of three members: Indra D'Mello, Austin Sequeira, and Mario Gonsalves in the president's seat.", "Evaluate and select beneficiaries for ICA's Taste of India Fundraiser.", "Ensure funds are distributed to beneficiaries in a timely manner.", "Confirm funds are used for their approved purposes and that project milestones are met."]],
  ["Core responsibilities", ["Read and evaluate Taste of India charity applications using ICA criteria and funding guidelines.", "Participate in committee meetings and discussions about charity applications.", "Work with fellow committee members to evaluate proposals and approve beneficiaries.", "Help ICA members navigate the process of submitting a charity application.", "Review project presentations, videos, reports, and supporting materials.", "Monitor awarded funds for compliance with funding agreements and approved purposes.", "Maintain applicant and beneficiary confidentiality when required."]],
  ["Time commitment and attendance", ["Service typically requires five to fifteen hours per month, depending on the grant cycle and workload.", "Members are expected to participate actively in scheduled meetings, held remotely or in person.", "Members should make reasonable efforts to attend meetings and complete assignments on time."]],
  ["Committee member qualifications", ["At least five years of ICA membership and a demonstrated understanding of ICA's mission and values.", "Objective, evidence-based evaluation and decision-making.", "Effective communication, active listening, and collaborative problem-solving.", "Integrity, transparency, and ethical decision-making.", "Commitment to ICA and the communities supported through its charitable work."]],
  ["Appointment process", ["When a vacancy exists, current committee members identify and recommend a qualified candidate.", "The recommendation is submitted to the ICA Board of Directors.", "The Board votes under ICA's parliamentary procedures and governing documents.", "The candidate is appointed after receiving the required Board approval."]],
  ["Terms, vacancies, and quorum", ["Members are tenured and serve at the discretion of the ICA Board of Directors, subject to ICA Bylaws and policies.", "There is no fixed term limit while a member remains in good standing and retains the Board's confidence.", "Vacancies are filled through the established appointment process.", "The committee must have at least three members, and three members are required for a quorum."]],
];
function Funds(){return <><PageIntro eyebrow="Taste of India" title="Funds Disbursement Committee"><p>The governing guidelines for evaluating Taste of India charity applications, selecting beneficiaries, distributing funds, and monitoring their use.</p><Button asChild variant="outline" className="mt-7"><Link to="/taste-of-india/about"><ArrowLeft size={16}/>Back to Taste of India</Link></Button></PageIntro><section className="site-container mx-auto max-w-4xl py-16"><div className="divide-y divide-border border-y border-border">{sections.map(([title,items])=><article className="py-8" key={title as string}><h2 className="font-display text-2xl font-semibold text-primary md:text-3xl">{title}</h2><ul className="mt-5 grid gap-3 text-muted-foreground">{(items as string[]).map(item=><li className="flex gap-3" key={item}><span className="mt-2 size-1.5 shrink-0 rounded-full bg-accent-foreground"/>{item}</li>)}</ul></article>)}</div></section></>}